M48
; DRILL file {KiCad 9.0.0} date 2026-01-22T12:53:34+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-01-22T12:53:34+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.3362Y-2.078
X5.3402Y-3.9736
X8.2878Y-2.0854
X8.5402Y-3.9768
M30
